"use client";
import Link from 'next/link';
import {useState} from 'react';
import {courses,courseYears,courseHref,courseTitle} from '@/lib/courses';
import {localizedPath,yearName,moduleTerm,money,tr,type Locale} from '@/lib/locale';
import {CourseCover} from '@/components/notebook/course-cover';
const normalize=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function CourseLibrary({year,locale='en'}:{year?:number;locale?:Locale}){
 const href=(p:string)=>localizedPath(p,locale),[query,setQuery]=useState(''),[type,setType]=useState('all');
 const selected=courses.filter(c=>(!year||c.year===year)&&normalize(Object.values(c.titles).join(' ')).includes(normalize(query.trim()))&&(type==='all'||c.category===type));
 return <div className="shell pb-24" dir={locale==='ar'?'rtl':'ltr'}><nav aria-label={tr(locale,'Academic years','Années d’études','السنوات الدراسية')} className="grid grid-cols-2 gap-3 md:grid-cols-3">{courseYears.map(n=><Link key={n} href={href(`/courses/year-${n}`)} aria-current={year===n?'page':undefined} className={`rounded-2xl border p-5 ${year===n?'border-ink bg-ink text-paper':'border-ink-12 hover:bg-ink-04'}`}><span className="text-xs opacity-60">{tr(locale,'MEDICINE','MÉDECINE','الطب')}</span><span className="mt-3 block text-2xl">{yearName(n,locale)} ↗</span><span className="mt-3 block text-xs opacity-60">{moduleTerm(n,locale)}</span></Link>)}</nav>
 <div className="mt-12 flex flex-wrap items-end justify-between gap-6 border-b border-ink-12 pb-6"><div><h2 className="text-2xl">{year&&year!==2&&year!==3?tr(locale,'Choose a module','Choisir un module','اختر وحدة'):tr(locale,'Choose a module / UEI','Choisir un module / UEI','اختر وحدة أو وحدة تعليمية مدمجة')}</h2><p className="mt-2 text-sm text-ink-56">{tr(locale,'Academic year → Module / UEI → Revision books','Année → Module / UEI → Livres de révision','السنة الدراسية ← الوحدة / الوحدة المدمجة ← كتب المراجعة')}</p></div><label className="w-full sm:w-72"><span className="mb-2 block text-xs">{tr(locale,'Find a module / book','Rechercher un module / livre','البحث عن وحدة أو كتاب')}</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} className="w-full rounded-xl border border-ink-12 bg-paper p-3"/></label></div>
 {(!year||year===2||year===3)&&<div className="my-6 flex flex-wrap gap-2">{[['all',tr(locale,'All','Tous','الكل')],['Modules',tr(locale,'Modules','Modules','الوحدات')],['Integrated units',tr(locale,'UEI','UEI','الوحدات التعليمية المدمجة')]].map(([value,label])=><button key={value} aria-pressed={type===value} onClick={()=>setType(value)} className={`min-h-11 rounded-full border px-5 text-sm ${type===value?'bg-ink text-paper':'border-ink-12'}`}>{label}</button>)}</div>}
 <p className="my-6 text-xs text-ink-56" aria-live="polite">{selected.length} {tr(locale,'books','livres','كتابًا')}</p>
 {(year?[year]:courseYears).map(n=>{const items=selected.filter(c=>c.year===n);return items.length?<section key={n} className="mb-12"><h3 className="mb-6 text-xl">{yearName(n,locale)} · {moduleTerm(n,locale)}</h3><ul className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{items.map(c=><li key={c.id} className="overflow-hidden rounded-2xl border border-ink-12"><Link href={href(courseHref(c))} aria-label={courseTitle(c,locale)} className="block bg-ink-04 px-12 py-9"><CourseCover course={c} locale={locale}/></Link><div className="p-5"><p className="text-xs text-ink-56">{c.category==='Integrated units'?tr(locale,'Integrated teaching unit (UEI)','Unité d’enseignement intégrée (UEI)','وحدة تعليمية مدمجة'):tr(locale,'Module','Module','وحدة')}</p><h4 className="mt-3 text-xl"><Link href={href(courseHref(c))}>{courseTitle(c,locale)}</Link></h4><p className="mt-3 font-medium">{money(c.price,locale)}</p><p className="mt-1 text-xs text-ink-56">{tr(locale,'Delivery not included','Hors livraison','دون رسوم التوصيل')}</p><div className="mt-6 grid grid-cols-2 gap-2"><Link className="wiz-control text-center" href={`${href(courseHref(c))}#preview`}>{tr(locale,'Preview','Aperçu','معاينة')}</Link><Link className="rounded-full bg-ink px-3 py-3 text-center text-sm text-paper" href={`${href(courseHref(c))}#order`}>{tr(locale,'View book','Voir le livre','عرض الكتاب')}</Link></div></div></li>)}</ul></section>:null;})}
 {!selected.length&&<div className="py-16 text-center"><p>{tr(locale,'No matching books.','Aucun livre ne correspond à votre recherche.','لا توجد كتب مطابقة للبحث.')}</p><button className="mt-5 underline" onClick={()=>{setQuery('');setType('all')}}>{tr(locale,'Reset filters','Réinitialiser les filtres','إعادة ضبط البحث')}</button></div>}</div>;
}
