"use client";
import Link from 'next/link';
import { useState } from 'react';
import { courses, courseYears, courseHref } from '@/lib/courses';
import { localizedPath, frenchYear, type Locale } from '@/lib/locale';
import { CourseCover } from '@/components/notebook/course-cover';
const normalize = (v: string) => v.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
export function CourseLibrary({ year, locale = 'en' }: { year?: number; locale?: Locale }) {
 const fr = locale === 'fr';
 const href = (p: string) => localizedPath(p, locale);
 const name = (n: number) => fr ? frenchYear(n) : `Year ${n}`;
 const [query,setQuery]=useState('');
 const [type,setType]=useState('all');
 const selected=courses.filter(c=>(!year||c.year===year)&&normalize(c.title).includes(normalize(query.trim()))&&(type==='all'||c.category===type));
 return <div className="shell pb-24">
 <nav aria-label={fr?'Années de médecine':'Medicine years'} className="grid grid-cols-2 gap-3 md:grid-cols-3">{courseYears.map(n=><Link key={n} href={href(`/courses/year-${n}`)} aria-current={year===n?'page':undefined} className={`rounded-2xl border p-5 ${year===n?'border-ink bg-ink text-paper':'border-ink-12 hover:bg-ink-04'}`}><span className="text-xs opacity-60">{fr?'MÉDECINE':'MEDICINE'}</span><span className="mt-3 block text-2xl">{name(n)} ↗</span><span className="mt-3 block text-xs opacity-60">{courses.some(c=>c.year===n)?`${courses.filter(c=>c.year===n).length} ${fr?'livres':'books'}`:fr?'Collection à venir':'Collection coming soon'}</span></Link>)}</nav>
 <div className="mt-12 flex flex-wrap items-end justify-between gap-6 border-b border-ink-12 pb-6"><div><h2 className="text-2xl">{fr?'La collection, année par année':'The collection, year by year'}</h2><p className="mt-2 text-sm text-ink-56">{fr?'Une matière ou une UEI. Un livre indépendant.':'One module or integrated unit. One independent book.'}</p></div><label className="w-full sm:w-72"><span className="mb-2 block text-xs">{fr?'Rechercher un livre':'Find a book'}</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={fr?'Matière, module ou UEI…':'Subject, module or unit…'} className="w-full rounded-xl border border-ink-12 bg-paper p-3"/></label></div>
 <div className="my-6 flex flex-wrap gap-2">{[['all',fr?'Tous':'All'],['Modules','Modules'],['Integrated units','UEI']].map(([value,label])=><button key={value} aria-pressed={type===value} onClick={()=>setType(value)} className={`min-h-11 rounded-full border px-5 text-sm ${type===value?'bg-ink text-paper':'border-ink-12'}`}>{label}</button>)}</div>
 <p className="mb-6 text-xs text-ink-56" aria-live="polite">{selected.length} {fr?'livres':'books'}</p>
 {(year?[year]:courseYears).map(n=>{const items=selected.filter(c=>c.year===n);if(!items.length)return null;return <section key={n} className="mb-12"><h3 className="mb-6 text-xl">{name(n)} · {fr?'Médecine':'Medicine'}</h3>{['Integrated units','Modules'].map(category=>{const group=items.filter(c=>c.category===category);return group.length?<div key={category} className="mb-10"><h4 className="mb-5 text-sm text-ink-56">{category==='Integrated units'?fr?'UEI — Unités d’enseignement intégrées':'UEI — Integrated teaching units':'Modules'}</h4><ul className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{group.map(c=><li key={c.id} className="overflow-hidden rounded-2xl border border-ink-12"><Link href={href(courseHref(c))} aria-label={`${fr?'Voir le livre':'View book'} ${c.title}`} className="block bg-ink-04 px-12 py-9"><CourseCover course={c} locale={locale}/></Link><div className="p-5"><p className="text-xs text-ink-56">{c.pages} pages · {fr?'Aperçu de 10 pages':'10-page preview'}</p><h5 className="mt-3 text-xl"><Link href={href(courseHref(c))}>{c.title}</Link></h5><div className="mt-6 grid grid-cols-2 gap-2"><Link className="wiz-control text-center" href={`${href(courseHref(c))}#preview`}>{fr?'Voir l’aperçu':'Preview'}</Link><Link className="rounded-full bg-ink px-3 py-3 text-center text-sm text-paper" href={`${href(courseHref(c))}#order`}>{fr?'Commander':'Order'}</Link></div></div></li>)}</ul></div>:null;})}</section>;})}
 {!selected.length&&<div className="py-16 text-center"><h3 className="text-xl">{year&&!courses.some(c=>c.year===year)?fr?'Cette collection se prépare.':'This collection is in preparation.':fr?'Aucun livre ne correspond à votre recherche.':'No books match your search.'}</h3><p className="mt-4 text-ink-56">{fr?'Les nouveaux livres seront ajoutés progressivement.':'New books will be added progressively.'}</p>{(query||type!=='all')&&<button className="mt-5 underline" onClick={()=>{setQuery('');setType('all');}}>{fr?'Réinitialiser les filtres':'Reset filters'}</button>}</div>}
 </div>;
}
