import Link from 'next/link';
import {courses,courseYears,courseHref,courseTitle} from '@/lib/courses';
import {yearName} from '@/lib/locale';
import {CourseCover} from './notebook/course-cover';
const concepts=[
 ['ملخصات دروس وليست دروسًا كاملة','يجمع كل كتاب ملخصات واضحة ومنظمة وفق البرنامج الجزائري، لتجد أساسيات الدرس بسهولة.'],
 ['فهرس يتحول إلى متتبع لتقدمك','يبدأ الكتاب بفهرس كامل للدروس يساعدك على الوصول إلى المحتوى، ويصبح أيضًا أداة لتتبع ما راجعته وما تبقى لك.'],
 ['صفحة للتعلم وأخرى مقابلة للتدوين','تقابل كل ملخص صفحة مخصصة لملاحظاتك. أضف شروحاتك ورسوماتك والنقاط المهمة مباشرة في الكتاب.'],
 ['مصمم وفق البرنامج الجزائري','الكتب مرتبة حسب السنة الدراسية والوحدة والوحدة التعليمية المدمجة، لتجد المحتوى بترتيب مألوف.'],
 ['أسلوب بخط يدوي وتصميم بسيط','خط مستوحى من الكتابة اليدوية، وأبيض وأسود، وصفحات مريحة تجعل الكتاب قريبًا من ملاحظاتك الشخصية.'],
 ['ملاحظات إضافية','يضم قسم الملاحظات الإضافية في نهاية الكتاب صفحات فارغة للكتابة بحرية وإضافة الشروحات والتذكيرات والرسومات، بنفس الأسلوب البسيط.'],
 ['مجموعة تتطور معك','MedWIZ — الطب هي أولى مجموعات THE WIZ. ستأتي مجموعات أخرى بنفس المبدأ: تحويل المعرفة إلى كتب عمل بسيطة ومنظمة وممتعة.'],
];
const faqs=[['كيف تُنظم الكتب؟','اختر السنة الدراسية، ثم الوحدة أو الوحدة التعليمية المدمجة، ثم كتاب المراجعة. كل كتاب مستقل ويتبع البرنامج الجزائري.'],['ما الذي يمكنني معاينته مجانًا؟','غلاف الكتاب ومقتطف من محتواه للتعرف على الملخصات وأسلوب الصفحات قبل الطلب.'],['كيف أطلب؟','أضف الكتب إلى السلة، أدخل بياناتك، اختر الولاية وطريقة التوصيل، ثم راجع الملخص والمبلغ الإجمالي وأكد الطلب.'],['كيف تُحسب رسوم التوصيل؟','تُحسب حسب الولاية وطريقة التوصيل: إلى المنزل أو الاستلام من مكتب النقل. تضاف مرة واحدة لكل طلب وبشكل مستقل عن أسعار الكتب. الوجهات غير المتاحة معطلة في القائمة.'],['هل عنوان المنزل مطلوب للاستلام من المكتب؟','لا. عنوان التوصيل مطلوب فقط عند اختيار التوصيل إلى المنزل.'],['هل توجد كتب جديدة مستقبلًا؟','تضاف كتب جديدة تدريجيًا. MedWIZ هي المجموعة الأولى وستتبعها مجموعات أخرى.']];
export function ArabicHome(){return <div lang="ar" dir="rtl"><section id="top" className="shell grid items-center gap-14 pb-24 pt-36 lg:grid-cols-[1.3fr_1fr]"><div><p className="type-eyebrow">مجموعات كتب للمراجعة</p><h1 className="mt-6 text-[clamp(3.5rem,12vw,9rem)]" dir="ltr">THE WIZ</h1><p className="mt-7 text-3xl">سنتك الدراسية. دروسك. كتابك.</p><p className="mt-6 max-w-lg leading-loose text-ink-56">كتب مراجعة ترافقك في كل سنة دراسية. ملخصات دروس منظمة وفق البرنامج الجزائري، وفهرس يتحول إلى متتبع للتقدم، وصفحات مخصصة لملاحظاتك.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/ar/courses" className="rounded-full bg-ink px-6 py-4 text-paper">اكتشف المجموعات ↗</Link><Link className="wiz-control px-6 py-4" href={'/ar'+courseHref(courses[0])}>تصفح كتابًا</Link></div><p className="mt-10 text-xs text-ink-56">ست سنوات في الطب · التوصيل إلى الولايات المتاحة</p></div><Link href={'/ar'+courseHref(courses[0])} className="mx-auto w-3/4 max-w-sm -rotate-3 py-6" aria-label={courseTitle(courses[0],'ar')}><CourseCover course={courses[0]} locale="ar"/></Link></section>
 <section id="why" className="shell border-t border-ink-12 py-20"><p className="type-eyebrow">لماذا THE WIZ؟</p><h2 className="mt-6 text-4xl">كتب مصممة للتعلم والتدوين والمراجعة.</h2><div className="mt-12 grid gap-10 md:grid-cols-2">{concepts.map(([title,body])=><article key={title} className="border-t border-ink-12 pt-6"><h3 className="text-2xl">{title}</h3><p className="mt-4 leading-loose text-ink-56">{body}</p></article>)}</div></section>
 <section className="shell py-20"><p className="type-eyebrow">المجموعة الأولى · MEDWIZ</p><h2 className="mt-6 text-4xl">الطب، سنة بعد سنة.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 md:grid-cols-3">{courseYears.map(n=><Link key={n} href={`/ar/courses/year-${n}`} className="rounded-2xl border border-ink-12 p-6"><h3 className="text-2xl">{yearName(n,'ar')} ↗</h3><p className="mt-4 text-sm text-ink-56">{n===2||n===3?'وحدات ووحدات تعليمية مدمجة':'وحدات'}</p></Link>)}</div></section>
 <section id="inside" className="shell py-20"><h2 className="text-4xl">تصفح قبل أن تختار.</h2><p className="mt-6 max-w-2xl leading-loose text-ink-56">فهرس لمتابعة التقدم، ملخصات دروس، صفحات ملاحظات مقابلة، ثم ملاحظات إضافية. اكتشف دفتر عمل حقيقيًا عبر هاتفك أو حاسوبك.</p><ol className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{['الفهرس / متتبع التقدم','ملخص الدرس','صفحة الملاحظات المقابلة','ملاحظات إضافية'].map(t=><li key={t} className="rounded-2xl border border-ink-12 p-6 text-xl">{t}</li>)}</ol><div className="mt-10 grid gap-8 sm:grid-cols-3">{courses.slice(0,3).map(c=><Link key={c.id} href={'/ar'+courseHref(c)+'#preview'} className="rounded-2xl bg-ink-04 p-10"><CourseCover course={c} locale="ar"/><p className="mt-8">معاينة {courseTitle(c,'ar')} ↗</p></Link>)}</div></section>
 <section id="order" className="shell py-20"><div className="rounded-2xl bg-ink p-8 text-paper"><h2 className="text-3xl">اختر كتابك القادم.</h2><p className="mt-5 leading-loose">أضف الكتب إلى السلة ثم اختر الولاية وطريقة التوصيل. راجع السعر النهائي قبل تأكيد طلبك.</p><Link className="mt-8 inline-block rounded-full bg-paper px-6 py-4 text-ink" href="/ar/courses">اختر كتابًا ↗</Link></div></section><section id="faq" className="shell py-20"><h2 className="text-4xl">الأسئلة الشائعة</h2><div className="mt-10">{faqs.map(([q,a])=><details key={q} className="border-t border-ink-12 py-6"><summary className="cursor-pointer text-lg">{q}</summary><p className="mt-4 max-w-3xl leading-loose text-ink-56">{a}</p></details>)}</div></section></div>}
