import Link from 'next/link';
import { CourseCover } from '@/components/notebook/course-cover';
import { courses, courseHref, courseYears } from '@/lib/courses';
import { frenchYear, localizedPath, type Locale } from '@/lib/locale';

export function CollectionHome({ locale = 'en' }: { locale?: Locale }) {
  const fr = locale === 'fr';
  const href = (p: string) => localizedPath(p, locale);
  const faqs = fr ? [
    ['Comment sont organisés les livres ?', 'Chaque année possède sa collection. Chaque module ou unité d’enseignement intégrée (UEI) correspond à un livre indépendant. Les UEI réunissent plusieurs disciplines autour d’un même thème.'],
    ['Que puis-je consulter gratuitement ?', 'La couverture et les dix premières pages de chaque livre. Le nombre total de pages est indiqué sur sa fiche, mais la suite ne fait pas partie de l’aperçu.'],
    ['Comment commander ?', 'Choisissez votre livre et cliquez sur « Commander par e-mail ». Nous confirmerons le prix, la disponibilité et les modalités avant toute commande.'],
    ['La livraison est-elle possible ?', 'Oui. Nous proposons la livraison à travers l’Algérie. Les modalités de livraison sont confirmées lors de la commande.'],
    ['De nouveaux livres sont-ils prévus ?', 'Oui. De nouveaux livres sont ajoutés progressivement et les éditions existantes peuvent être améliorées.'],
  ] : [
    ['How are the books organized?', 'Each year has its own collection. Each module or integrated teaching unit (UEI) is an independent book. Integrated units bring together several disciplines around one theme.'],
    ['What can I preview?', 'The cover and the first ten pages of each book. Its full page count appears on the product page, but the remaining pages are not included in the preview.'],
    ['How do I order?', 'Choose a book and select “Order by email”. We will confirm price, availability and delivery details before you order.'],
    ['Is delivery available?', 'Yes. We offer delivery across Algeria. Delivery arrangements are confirmed when ordering.'],
    ['Will there be new books?', 'New books are added progressively, and existing editions may be improved.'],
  ];
  return <div lang={locale}>
    <section id="top" className="shell grid items-center gap-14 pb-24 pt-32 md:pt-44 lg:grid-cols-[1.3fr_1fr]">
      <div><p className="type-eyebrow">{fr ? 'LA COLLECTION MÉDECINE' : 'THE MEDICINE COLLECTION'}</p><h1 className="type-display mt-6 text-[clamp(3.5rem,12vw,9rem)]">THE WIZ</h1><p className="mt-7 max-w-xl text-3xl leading-tight">{fr ? 'Votre année. Votre matière. Votre livre.' : 'Your year. Your subject. Your book.'}</p><p className="mt-6 max-w-lg leading-relaxed text-ink-56">{fr ? 'Des livres de révision indépendants, organisés par année, module et UEI. Découvrez chaque couverture, feuilletez dix pages et choisissez votre prochain livre.' : 'Independent study books organized by year, module and integrated unit. Explore each cover, turn through ten pages and choose your next book.'}</p><div className="mt-9 flex flex-wrap gap-3"><Link className="rounded-full bg-ink px-6 py-4 text-paper" href={href('/courses')}>{fr ? 'Découvrir les livres' : 'Explore the books'} ↗</Link><Link className="wiz-control px-6 py-4" href={href(courseHref(courses[0]))}>{fr ? 'Feuilleter un livre' : 'Preview a book'}</Link></div><p className="mt-10 text-xs text-ink-56">{fr ? '6 années de médecine · Livraison à travers l’Algérie' : '6 years of medicine · Delivery across Algeria'}</p></div>
      <Link href={href(courseHref(courses[0]))} aria-label={fr ? 'Découvrir Biostatistiques' : 'Explore Biostatistiques'} className="mx-auto w-[75%] max-w-sm -rotate-3 py-6"><CourseCover course={courses[0]} locale={locale}/></Link>
    </section>
    <section id="why" className="shell border-t border-ink-12 py-20"><p className="type-eyebrow">{fr ? 'POURQUOI THE WIZ' : 'WHY THE WIZ'}</p><h2 className="mt-6 text-4xl">{fr ? 'Une collection qui suit votre année.' : 'A collection that follows your year.'}</h2><div className="mt-12 grid gap-8 md:grid-cols-3">{(fr ? [['01','Un livre par matière','Chaque livre a sa propre couverture, sa fiche et son aperçu. Vous choisissez précisément ce dont vous avez besoin.'],['02','Modules et UEI','Les modules classiques restent distincts des unités d’enseignement intégrées, selon l’organisation de votre année.'],['03','Un vrai livre à découvrir','Une couverture minimaliste, une spirale noire en plastique et des pages à feuilleter avant de commander.']] : [['01','One book per subject','Each book has its own cover, product page and preview. Choose exactly what you need.'],['02','Modules and integrated units','Standard modules remain distinct from integrated teaching units, following the organization of your year.'],['03','A book you can explore','A minimal cover, a black plastic spiral and pages to turn before ordering.']]).map(([n,title,body])=><div key={n} className="border-t border-ink-12 pt-6"><p className="text-xs text-ink-56">{n}</p><h3 className="mt-5 text-2xl">{title}</h3><p className="mt-4 leading-relaxed text-ink-56">{body}</p></div>)}</div></section>
    <section id="series" className="shell py-20"><p className="type-eyebrow">{fr ? 'LES ANNÉES' : 'THE YEARS'}</p><h2 className="mt-6 text-4xl">{fr ? 'Chaque année, sa collection.' : 'Every year has its collection.'}</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 md:grid-cols-3">{courseYears.map(n=><Link key={n} href={href(`/courses/year-${n}`)} className="rounded-2xl border border-ink-12 p-6 hover:bg-ink-04"><h3 className="text-2xl">{fr ? `${frenchYear(n)} médecine` : `Medicine · Year ${n}`} ↗</h3><p className="mt-4 text-sm text-ink-56">{courses.some(c=>c.year===n) ? `${courses.filter(c=>c.year===n).length} ${fr?'livres à découvrir':'books to explore'}` : fr?'Collection à venir':'Collection coming soon'}</p></Link>)}</div></section>
    <section id="inside" className="shell py-20"><p className="type-eyebrow">{fr ? 'À L’INTÉRIEUR' : 'INSIDE'}</p><h2 className="mt-6 text-4xl">{fr ? 'Feuilletez avant de choisir.' : 'Turn the pages before choosing.'}</h2><p className="mt-6 max-w-2xl leading-relaxed text-ink-56">{fr ? 'Consultez les dix premières pages sur téléphone ou ordinateur. Balayez pour avancer, revenez à la couverture et découvrez chaque livre à votre rythme.' : 'Read the first ten pages on your phone or computer. Swipe forward, return to the cover and explore each book at your own pace.'}</p><div className="mt-10 grid gap-8 sm:grid-cols-3">{courses.slice(0,3).map(c=><Link key={c.id} href={`${href(courseHref(c))}#preview`} className="rounded-2xl bg-ink-04 p-10"><CourseCover course={c} locale={locale}/><p className="mt-8 text-sm">{fr ? 'Voir l’aperçu' : 'Preview'} ↗</p></Link>)}</div></section>
    <section id="order" className="shell py-20"><div className="rounded-2xl bg-ink p-8 text-paper sm:p-12"><h2 className="text-3xl">{fr ? 'Choisissez votre prochain livre.' : 'Choose your next book.'}</h2><p className="mt-5 max-w-xl leading-relaxed opacity-70">{fr ? 'Chaque fiche vous permet de demander votre livre par e-mail. Prix, disponibilité et livraison sont confirmés lors de la commande.' : 'Request your book by email from its product page. Price, availability and delivery are confirmed when ordering.'}</p><Link className="mt-8 inline-block rounded-full bg-paper px-6 py-4 text-ink" href={href('/courses')}>{fr ? 'Choisir un livre' : 'Choose a book'} ↗</Link></div></section>
    <section id="faq" className="shell py-20"><p className="type-eyebrow">FAQ</p><h2 className="mt-6 text-4xl">{fr ? 'Vos questions, nos réponses.' : 'Your questions, answered.'}</h2><div className="mt-10">{faqs.map(([q,a])=><details key={q} className="border-t border-ink-12 py-6"><summary className="cursor-pointer text-lg">{q}</summary><p className="mt-4 max-w-3xl leading-relaxed text-ink-56">{a}</p></details>)}</div></section>
  </div>;
}
