import { Notebook3D } from './notebook/notebook-3d';
import { assetPath } from '@/lib/hosting';
import { BookConcept, BookStructure } from './book-concept';
import Link from 'next/link';
import { CourseCover } from '@/components/notebook/course-cover';
import { courses, courseHref, courseYears } from '@/lib/courses';
import { frenchYear, localizedPath, type Locale } from '@/lib/locale';

export function CollectionHome({ locale = 'en' }: { locale?: Locale }) {
  const fr = locale === 'fr';
  const href = (p: string) => localizedPath(p, locale);
  const faqs = fr ? [
    ['Comment sont organisés les livres ?', 'MedWIZ — Médecine est la première collection de THE WIZ, organisée par année selon le programme algérien. Chaque module ou unité d’enseignement intégrée (UEI) correspond à un livre indépendant. Les UEI réunissent plusieurs disciplines autour d’un même thème.'],
    ['Que puis-je consulter gratuitement ?', 'La couverture et un extrait de chaque livre. Découvrez les résumés de cours et le style du livre avant de commander.'],
    ['Comment commander ?', 'Ajoutez vos livres au panier et remplissez le formulaire de livraison. Choisissez la wilaya et le mode de livraison, puis vérifiez le total avant de confirmer.'],
    ['La livraison est-elle possible ?', 'Choisissez la livraison à domicile ou le retrait Stopdesk. Les frais dépendent de la wilaya et du mode choisi, et sont ajoutés une seule fois par commande. Les destinations indisponibles sont indiquées.'],
    ['De nouveaux livres sont-ils prévus ?', 'Oui. De nouveaux livres sont ajoutés progressivement et les éditions existantes peuvent être améliorées.'],
  ] : [
    ['How are the books organized?', 'MedWIZ — Medicine is THE WIZ’s first collection, organized by year according to the Algerian curriculum. Each module or integrated teaching unit (UEI) is an independent book. Integrated units bring together several disciplines around one theme.'],
    ['What can I preview?', 'The cover and an excerpt from each book. Explore the course summaries and book style before ordering.'],
    ['How do I order?', 'Add your books to the cart and complete the delivery form. Choose your wilaya and delivery method, then review the exact total before confirming.'],
    ['Is delivery available?', 'Choose home delivery or stopdesk pickup. The fee depends on wilaya and delivery method and is charged once per order. Unavailable destinations are marked.'],
    ['Will there be new books?', 'New books are added progressively, and existing editions may be improved.'],
  ];
  return <div lang={locale}>
    <section id="top" className="shell grid items-center gap-14 pb-24 pt-32 md:pt-44 lg:grid-cols-[1.3fr_1fr]">
      <div><p className="type-eyebrow">{fr ? 'DES COLLECTIONS POUR RÉVISER' : 'COLLECTIONS FOR YOUR STUDIES'}</p><h1 className="type-display mt-6 text-[clamp(3.5rem,12vw,9rem)]">THE WIZ</h1><p className="mt-7 max-w-xl text-3xl leading-tight">{fr ? 'Votre année. Vos cours. Votre livre.' : 'Your year. Your courses. Your book.'}</p><p className="mt-6 max-w-lg leading-relaxed text-ink-56">{fr ? 'Des livres de révision pensés pour accompagner chaque année d’études. Des résumés de cours organisés selon le programme algérien, un sommaire qui devient un tracker de progression et des pages dédiées à vos propres notes.' : 'Revision books designed to support every year of study. Course summaries organized according to the Algerian curriculum, contents that become a progress tracker, and dedicated space for your own notes.'}</p><div className="hero-actions mt-9"><Link className="hero-action hero-action-primary" href={href('/courses')}>{fr ? 'Découvrir les collections' : 'Explore the collections'} ↗</Link><Link className="hero-action hero-action-secondary" href={href(courseHref(courses[0]))}>{fr ? 'Feuilleter un livre' : 'Preview a book'}</Link></div><p className="mt-10 text-xs text-ink-56">{fr ? '6 années de médecine · Livraison à travers l’Algérie' : '6 years of medicine · Delivery across Algeria'}</p></div>
      <Link href={href(courseHref(courses[0]))} aria-label={fr ? 'Découvrir Biostatistiques' : 'Explore Biostatistiques'} className="block w-full min-w-0 py-6"><Notebook3D coverSrc={assetPath(`/course-pages/${courses[0].id}/1.webp`)} coverAlt={courses[0].title}/></Link>
    </section>
    <BookConcept locale={locale} />
    <section id="series" className="shell py-20"><p className="type-eyebrow">{fr ? 'PREMIÈRE COLLECTION · MEDWIZ' : 'FIRST COLLECTION · MEDWIZ'}</p><h2 className="mt-6 text-4xl">{fr ? 'MedWIZ — Médecine, année par année.' : 'MedWIZ — Medicine, year by year.'}</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 md:grid-cols-3">{courseYears.map(n=><Link key={n} href={href(`/courses/year-${n}`)} className="rounded-2xl border border-ink-12 p-6 hover:bg-ink-04"><h3 className="text-2xl">{fr ? `${frenchYear(n)} médecine` : `Medicine · Year ${n}`} ↗</h3><p className="mt-4 text-sm text-ink-56">{courses.some(c=>c.year===n) ? `${courses.filter(c=>c.year===n).length} ${fr?'livres à découvrir':'books to explore'}` : fr?'Livres à venir':'Books coming soon'}</p></Link>)}</div></section>
    <section id="inside" className="shell py-20"><p className="type-eyebrow">{fr ? 'À L’INTÉRIEUR' : 'INSIDE'}</p><h2 className="mt-6 text-4xl">{fr ? 'Feuilletez avant de choisir.' : 'Turn the pages before choosing.'}</h2><p className="mt-6 max-w-2xl leading-relaxed text-ink-56">{fr ? 'Du sommaire qui devient votre tracker aux résumés et leurs pages de notes en face, jusqu’aux Extra Notes : découvrez un véritable livre de travail. Feuilletez un extrait sur téléphone ou ordinateur.' : 'From contents that become your tracker to summaries with facing notes pages and Extra Notes: explore a real study book. Preview an excerpt on your phone or computer.'}</p><BookStructure locale={locale}/><div className="mt-10 grid gap-8 sm:grid-cols-3">{courses.slice(0,3).map(c=><Link key={c.id} href={`${href(courseHref(c))}#preview`} className="rounded-2xl bg-ink-04 p-10"><CourseCover course={c} locale={locale}/><p className="mt-8 text-sm">{fr ? 'Voir l’aperçu' : 'Preview'} ↗</p></Link>)}</div></section>
    <section id="order" className="shell py-20"><div className="rounded-2xl bg-ink p-8 text-paper sm:p-12"><h2 className="text-3xl">{fr ? 'Choisissez votre prochain livre.' : 'Choose your next book.'}</h2><p className="mt-5 max-w-xl leading-relaxed opacity-70">{fr ? 'Ajoutez vos livres au panier puis remplissez vos coordonnées de livraison. Les prix des livres et les frais de livraison sont détaillés avant confirmation.' : 'Add books to your cart, then enter your delivery details. Book prices and delivery fees are shown separately before confirmation.'}</p><Link className="mt-8 inline-block rounded-full bg-paper px-6 py-4 text-ink" href={href('/courses')}>{fr ? 'Choisir un livre' : 'Choose a book'} ↗</Link></div></section>
    <section id="faq" className="shell py-20"><p className="type-eyebrow">FAQ</p><h2 className="mt-6 text-4xl">{fr ? 'Vos questions, nos réponses.' : 'Your questions, answered.'}</h2><div className="mt-10">{faqs.map(([q,a])=><details key={q} className="border-t border-ink-12 py-6"><summary className="cursor-pointer text-lg">{q}</summary><p className="mt-4 max-w-3xl leading-relaxed text-ink-56">{a}</p></details>)}</div></section>
  </div>;
}
