"use client";
import { useEffect, useState, type FormEvent } from 'react';
import { githubPages } from '@/lib/hosting';
import { orderItems, orderStatuses, statusLabels, type Order, type OrderStatus } from '@/lib/order-types';

export function AdminOrders() {
  const [authenticated,setAuthenticated]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [orders,setOrders]=useState<Order[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState('all');
  async function refresh() {
    setError('');setBusy(true);
    try { const res=await fetch('/api/admin/orders',{cache:'no-store'}); const data=await res.json(); if(res.status===401){setAuthenticated(false);setOrders([]);throw new Error('Session expirée. Reconnectez-vous.');}if(!res.ok)throw new Error(data.error);setOrders(data.orders); }
    catch(e){setError(e instanceof Error?e.message:'Erreur réseau');}finally{setBusy(false);}
  }
  useEffect(()=>{if(githubPages){setLoading(false);return;}fetch('/api/admin/session',{cache:'no-store'}).then(r=>r.json()).then(data=>{setAuthenticated(data.authenticated);if(!data.configured)setError('Définissez WIZ_ADMIN_PASSWORD sur le serveur pour activer les commandes.');if(data.authenticated)void refresh();}).catch(()=>setError('Connexion au serveur impossible.')).finally(()=>setLoading(false));},[]);
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');try{const r=await fetch('/api/admin/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:new FormData(form).get('password')})});const d=await r.json();if(!r.ok)throw new Error(d.error);form.reset();setAuthenticated(true);await refresh();}catch(e){setError(e instanceof Error?e.message:'Erreur réseau');}finally{setBusy(false);}}
  async function logout(){setBusy(true);try{const r=await fetch('/api/admin/session',{method:'DELETE'});if(!r.ok)throw new Error('Déconnexion impossible.');setAuthenticated(false);setOrders([]);}catch(e){setError(e instanceof Error?e.message:'Erreur réseau');}finally{setBusy(false);}}
  async function update(id:string,next:OrderStatus){setBusy(true);setError('');try{const r=await fetch('/api/admin/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:next})});const d=await r.json();if(!r.ok)throw new Error(d.error);setOrders(previous=>previous.map(o=>o.id===id?d.order:o));}catch(e){setError(e instanceof Error?e.message:'Erreur réseau');}finally{setBusy(false);}}
  async function download(){setBusy(true);setError('');try{const r=await fetch('/api/admin/orders?export=csv',{cache:'no-store'});if(!r.ok)throw new Error('Export impossible. Reconnectez-vous puis réessayez.');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`the-wiz-commandes-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Erreur réseau');}finally{setBusy(false);}}
  const visible=orders.filter(o=>(status==='all'||o.status===status)&&[o.reference,o.name,o.phone,o.title,o.wilaya,o.email].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <section className="shell min-h-[70vh] pb-24 pt-32" lang="fr"><p className="type-eyebrow">THE WIZ · ESPACE PRIVÉ</p><h1 className="mt-5 text-4xl">Commandes</h1>
    {githubPages?<p className="mt-8">L’administration est disponible sur la version Netlify du site.</p>:loading?<p className="mt-8" role="status">Chargement…</p>:!authenticated?<form onSubmit={login} className="mt-8 max-w-md space-y-5 rounded-2xl border border-ink-12 p-6"><h2 className="text-xl">Connexion administrateur</h2><label className="block">Mot de passe<input name="password" type="password" autoComplete="current-password" required className="mt-3 w-full rounded-xl border border-ink-24 p-3"/></label><button disabled={busy} className="w-full rounded-full bg-ink p-3 text-paper disabled:opacity-50">{busy?'Connexion…':'Se connecter'}</button></form>:<>
      <div className="mt-7 flex flex-wrap gap-3"><button disabled={busy} className="wiz-control" onClick={refresh}>Actualiser</button><button disabled={busy} className="rounded-full bg-ink px-5 py-3 text-sm text-paper disabled:opacity-50" onClick={download}>Exporter toutes les commandes — Excel (CSV)</button><button disabled={busy} className="wiz-control" onClick={logout}>Déconnexion</button></div>
      <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3">{[['Total',orders.length],['Nouvelles',orders.filter(o=>o.status==='new').length],['Livres demandés',orders.reduce((sum,o)=>sum+o.quantity,0)]].map(([label,value])=><div key={label} className="rounded-xl border border-ink-12 p-5"><p className="text-xs text-ink-56">{label}</p><p className="mt-2 text-3xl">{value}</p></div>)}</div>
      <div className="my-8 flex flex-wrap gap-4"><label className="flex-1 text-sm">Rechercher<input className="mt-2 block w-full min-w-48 rounded-xl border border-ink-24 p-3" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom, téléphone, livre, wilaya…"/></label><label className="text-sm">Statut<select value={status} onChange={e=>setStatus(e.target.value)} className="mt-2 block rounded-xl border border-ink-24 p-3"><option value="all">Tous</option>{orderStatuses.map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></label></div>
      <p className="mb-4 text-sm text-ink-56" aria-live="polite">{visible.length} commande(s) affichée(s). L’export inclut toutes les commandes.</p>
      <div className="overflow-x-auto rounded-xl border border-ink-12" tabIndex={0} role="region" aria-label="Tableau des commandes"><table className="w-full min-w-[1000px] text-left text-sm"><caption className="sr-only">Commandes THE WIZ</caption><thead className="bg-ink-04"><tr>{['Date / Référence','Livre','Client','Livraison','Note','Statut'].map(h=><th key={h} scope="col" className="p-4 font-medium">{h}</th>)}</tr></thead><tbody>{visible.map(o=><tr key={o.id} className="border-t border-ink-12 align-top"><td className="p-4"><p>{new Date(o.createdAt).toLocaleString('fr-DZ')}</p><p className="mt-2 max-w-40 break-all text-xs text-ink-56">{o.reference}</p></td><td className="p-4">{orderItems(o).map(i=><div key={i.courseId} className="mb-3"><p>{i.title}</p><p className="mt-2 text-ink-56">Année {i.year} · Quantité {i.quantity}</p></div>)}</td><td className="p-4"><p>{o.name}</p><p className="mt-2">{o.phone}</p><p className="mt-2 max-w-52 break-words">{o.email}</p></td><td className="p-4"><p>{o.wilaya}</p><p className="mt-2 max-w-64 whitespace-pre-wrap break-words">{o.address}</p></td><td className="max-w-64 whitespace-pre-wrap break-words p-4">{o.note||'—'}</td><td className="p-4"><select aria-label={`Statut de ${o.reference}`} disabled={busy} value={o.status} onChange={e=>update(o.id,e.target.value as OrderStatus)} className="rounded-lg border border-ink-24 p-2">{orderStatuses.map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></td></tr>)}</tbody></table></div>
      {!visible.length&&<p className="py-10 text-center">{orders.length?'Aucune commande ne correspond aux filtres.':'Aucune commande reçue pour le moment.'}</p>}
    </>}{error&&<p role="alert" className="mt-6 rounded-xl border border-ink-24 p-4">{error}</p>}
  </section>;
}
