"use client";
import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {usePathname} from 'next/navigation';
import Link from 'next/link';
import {products as courses,productTitle as courseTitle} from '@/lib/offers';
import {localeFromPath,localizedPath,money,yearName} from '@/lib/locale';
import {checkoutCopy,emptyDraft} from '@/lib/checkout-copy';
import type {CartItem} from '@/lib/commerce';
import {CourseOrderForm} from './course-order-form';
import {LanguageSwitch} from '@/components/layout/language-switch';
const CartContext=createContext<{add:(id:string)=>void;open:()=>void;count:number}>({add:()=>{},open:()=>{},count:0});
export const useCart=()=>useContext(CartContext);
export function CartProvider({children}:{children:ReactNode}){
 const pathname=usePathname(),locale=localeFromPath(pathname),t=checkoutCopy(locale);
 const [items,setItems]=useState<CartItem[]>([]),[loaded,setLoaded]=useState(false),[checkout,setCheckout]=useState(false),[draft,setDraft]=useState(emptyDraft),[busy,setBusy]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('wiz-cart')||'[]');if(Array.isArray(saved))setItems(saved.filter((i:CartItem)=>i&&courses.some(c=>c.id===i.courseId&&c.available)&&Number.isInteger(i.quantity)&&i.quantity>0&&i.quantity<=20).filter((i:CartItem,n:number,a:CartItem[])=>a.findIndex(j=>j.courseId===i.courseId)===n));const savedDelivery=JSON.parse(localStorage.getItem('wiz-delivery')||'null');if(savedDelivery&&typeof savedDelivery.wilayaId==='string'&&['home','stopdesk'].includes(savedDelivery.deliveryMethod))setDraft(d=>({...d,...{wilayaId:savedDelivery.wilayaId,deliveryMethod:savedDelivery.deliveryMethod}}));}catch{}setLoaded(true);},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('wiz-cart',JSON.stringify(items));localStorage.setItem('wiz-delivery',JSON.stringify({wilayaId:draft.wilayaId,deliveryMethod:draft.deliveryMethod}));}catch{}},[items,loaded,draft.wilayaId,draft.deliveryMethod]);
 function open(){if(busy)return;setCheckout(false);dialog.current?.showModal();}
 function add(id:string){if(!loaded||busy||!courses.some(c=>c.id===id&&c.available))return;setItems(old=>old.some(i=>i.courseId===id)?old.map(i=>i.courseId===id?{...i,quantity:Math.min(20,i.quantity+1)}:i):[...old,{courseId:id,quantity:1}]);open();}
 const count=items.reduce((n,i)=>n+i.quantity,0),subtotal=items.reduce((n,i)=>n+courses.find(c=>c.id===i.courseId)!.price*i.quantity,0);
 return <CartContext.Provider value={{add,open,count}}>{children}{pathname!=='/admin'&&<button onClick={open} disabled={!loaded||busy} className="fixed bottom-[calc(5rem+env(safe-area-inset-bottom,0px))] end-5 z-40 rounded-full bg-ink px-6 py-4 text-paper shadow-xl" aria-label={`${t.cart} (${count})`}>{t.cart} · {count}</button>}
 <dialog ref={dialog} data-lenis-prevent lang={locale} dir={locale==='ar'?'rtl':'ltr'} onCancel={e=>{if(busy)e.preventDefault()}} className="m-auto max-h-[90dvh] w-[calc(100%-2rem)] max-w-2xl overflow-y-auto rounded-3xl bg-paper p-6 text-start text-ink shadow-2xl backdrop:bg-black/40 sm:p-8" aria-labelledby="cart-title"><div className="sticky top-0 z-10 flex flex-wrap items-center justify-between gap-3 bg-paper py-2"><h2 id="cart-title" className="text-2xl">{t.yourCart}</h2><LanguageSwitch/><button disabled={busy} className="wiz-control" onClick={()=>dialog.current?.close()} aria-label={t.close}>✕</button></div>
 {checkout?<><button disabled={busy} className="mt-5 text-sm underline" onClick={()=>setCheckout(false)}>{t.back}</button><CourseOrderForm locale={locale} items={items} draft={draft} setDraft={setDraft} onBusy={setBusy} onSaved={()=>{setItems([]);setDraft(emptyDraft)}}/></>:!items.length?<div className="py-12 text-center"><p>{t.empty}</p><Link className="mt-6 inline-block underline" href={localizedPath('/courses',locale)} onClick={()=>dialog.current?.close()}>{t.browse}</Link></div>:<><ul className="mt-6 divide-y divide-ink-12">{items.map(item=>{const course=courses.find(c=>c.id===item.courseId)!;return <li key={item.courseId} className="flex gap-4 py-5"><img src={course.image} alt="" width={64} height={90} className="h-24 w-16 rounded object-cover"/><div className="min-w-0 flex-1"><h3 className="font-medium">{courseTitle(course,locale)}</h3><p className="mt-1 text-sm text-ink-56">{course.year?yearName(course.year,locale):t.books} · {t.unit}: {money(course.price,locale)}</p><div className="mt-3 flex flex-wrap items-center gap-4"><label className="text-sm">{t.quantity} <select aria-label={`${t.quantity} — ${courseTitle(course,locale)}`} value={item.quantity} onChange={e=>setItems(old=>old.map(i=>i.courseId===item.courseId?{...i,quantity:Number(e.target.value)}:i))} className="rounded-lg border border-ink-24 p-2">{Array.from({length:20},(_,n)=><option key={n+1}>{n+1}</option>)}</select></label><button onClick={()=>setItems(old=>old.filter(i=>i.courseId!==item.courseId))} className="text-sm underline">{t.remove}</button><bdi>{money(course.price*item.quantity,locale)}</bdi></div></div></li>})}</ul><div className="mt-5 border-t border-ink-12 pt-5"><p className="flex justify-between gap-4 font-medium"><span>{t.subtotal}</span><bdi>{money(subtotal,locale)}</bdi></p><p className="mt-3 text-sm text-ink-56">{t.separate}</p><button onClick={()=>setCheckout(true)} className="mt-5 w-full rounded-full bg-ink p-4 text-paper">{t.checkout}</button><button onClick={()=>dialog.current?.close()} className="mt-3 w-full p-3 text-sm underline">{t.continue}</button></div></>}
 </dialog></CartContext.Provider>;
}
