"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {quote,deliveryRates,type CartItem} from '@/lib/commerce';
import {products as courses,productTitle as courseTitle} from '@/lib/offers';
import {money,type Locale} from '@/lib/locale';
import {checkoutCopy,type CheckoutDraft} from '@/lib/checkout-copy';
import {githubPages} from '@/lib/hosting';
type Pricing=NonNullable<ReturnType<typeof quote>>;
export function OrderSummary({pricing,draft,locale}:{pricing:Pricing;draft:CheckoutDraft;locale:Locale}){
 const t=checkoutCopy(locale),rate=deliveryRates.find(r=>r.id===pricing.wilayaId)!;
 return <div className="space-y-5 rounded-2xl border border-ink-12 p-5"><h3 className="text-xl">{t.summary}</h3><section><h4 className="font-medium">{t.customer}</h4><p>{draft.firstName} {draft.lastName}</p><p dir="ltr" className="text-start">{draft.phone}</p>{draft.phone2&&<p dir="ltr" className="text-start">{draft.phone2}</p>}<p className="break-all">{draft.email}</p></section><section><h4 className="font-medium">{t.shipment}</h4><p>{rate.name[locale]} · {pricing.deliveryMethod==='home'?t.home:t.stopdesk}</p><p className="whitespace-pre-wrap break-words">{pricing.deliveryMethod==='home'?draft.address:t.pickup}</p></section><section><h4 className="font-medium">{t.books}</h4><ul className="divide-y divide-ink-12">{pricing.items.map(i=><li key={i.courseId} className="py-3"><p>{courseTitle(courses.find(c=>c.id===i.courseId)!,locale)}</p><p className="text-sm">{t.quantity}: {i.quantity} · {t.unit}: {money(i.unitPrice,locale)}</p><p>{money(i.lineTotal,locale)}</p>{i.includedBooks.length>1&&<details className="mt-2 text-xs"><summary className="cursor-pointer underline">{i.includedBooks.length} {t.books}</summary><ul className="mt-2 space-y-1">{i.includedBooks.map(b=><li key={b.courseId}>{courseTitle(courses.find(c=>c.id===b.courseId)!,locale)} × {b.quantity*i.quantity}</li>)}</ul></details>}</li>)}</ul></section><Totals pricing={pricing} locale={locale}/>{draft.note&&<p className="whitespace-pre-wrap break-words">{t.note}: {draft.note}</p>}</div>;
}
export function Totals({pricing,locale}:{pricing:Pricing;locale:Locale}){const t=checkoutCopy(locale);return <dl className="space-y-3 border-t border-ink-12 pt-4">{[[t.subtotal,pricing.subtotal],[t.delivery,pricing.deliveryFee],[t.total,pricing.total]].map(([label,value],i)=><div key={label} className={`flex flex-wrap justify-between gap-3 ${i===2?'border-t border-ink-12 pt-4 text-xl font-semibold':''}`}><dt>{label}</dt><dd>{money(Number(value),locale)}</dd></div>)}</dl>}
export function CourseOrderForm({locale,items,draft,setDraft,onSaved,onBusy}:{locale:Locale;items:CartItem[];draft:CheckoutDraft;setDraft:(d:CheckoutDraft)=>void;onSaved:()=>void;onBusy:(busy:boolean)=>void}){
 const t=checkoutCopy(locale),[ready,setReady]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<'error'|'invalid'|'limited'|''>(''),[review,setReview]=useState(false),[receipt,setReceipt]=useState<{reference:string;pricing:Pricing;draft:CheckoutDraft}|null>(null);
 const container=useRef<HTMLDivElement>(null);
 useEffect(()=>{container.current?.closest('dialog')?.scrollTo({top:0});},[review,receipt]);
 const attempt=useRef({id:'',signature:''}),sending=useRef(false),honeypot=useRef<HTMLInputElement>(null);
 const pricing=quote(items,draft.wilayaId,draft.deliveryMethod);
 async function check(){setReady(null);if(githubPages){setReady(false);return;}try{const r=await fetch('/api/order',{cache:'no-store'});setReady(r.ok&&(await r.json()).available===true);}catch{setReady(false)}}
 useEffect(()=>{void check();},[]);
 const update=(key:keyof CheckoutDraft,value:string|boolean)=>{setDraft({...draft,[key]:value});setError('');};
 function reviewOrder(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!e.currentTarget.checkValidity()||!pricing||(draft.phone2.trim()&&(!/^[+\d ()-]{7,24}$/.test(draft.phone2)||draft.phone2.replace(/\D/g,'').length<7))||!draft.firstName.trim()||!draft.lastName.trim()||!/^[+\d ()-]{7,24}$/.test(draft.phone)||draft.phone.replace(/\D/g,'').length<7||(draft.deliveryMethod==='home'&&draft.address.trim().length<5)){setError('invalid');return;}setError('');setReview(true);}
 async function submit(){if(!pricing||sending.current||!ready)return;sending.current=true;setBusy(true);onBusy(true);setError('');const payload={...draft,address:draft.deliveryMethod==='home'?draft.address:'',items,expectedTotal:pricing.total,website:honeypot.current?.value||''};const signature=JSON.stringify(payload);if(attempt.current.signature!==signature)attempt.current={id:crypto.randomUUID(),signature};try{const r=await fetch('/api/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,id:attempt.current.id})});const data=await r.json();if(!r.ok){setError(r.status===429?'limited':'error');return;}setReceipt({reference:data.reference,pricing,draft:{...draft}});onSaved();}catch{setError('error')}finally{sending.current=false;setBusy(false);onBusy(false)}}
 if(receipt)return <div ref={container} className="mt-6 space-y-5"><div role="status"><h3 className="text-xl">{t.saved}</h3><p className="mt-3 break-all">{t.reference}: <bdi>{receipt.reference}</bdi></p><p className="mt-3 text-sm text-ink-56">{t.contact}</p></div><OrderSummary {...receipt} locale={locale}/></div>;
 return <div ref={container} className="mt-6 space-y-5">{ready!==true&&<div role="status" className="rounded-xl bg-ink-04 p-4 text-sm">{ready===null?t.loading:t.service}{ready===false&&<button onClick={check} className="mt-3 block underline">{t.retry}</button>}</div>}
 {review&&pricing?<><OrderSummary pricing={pricing} draft={draft} locale={locale}/><button disabled={busy} className="wiz-control" onClick={()=>setReview(false)}>{t.edit}</button><button onClick={submit} disabled={busy||!ready} className="w-full rounded-full bg-ink p-4 text-paper disabled:opacity-50">{busy?t.saving:t.confirm}</button></>:<form noValidate onSubmit={reviewOrder} className="space-y-4"><h3 className="text-xl">{t.details}</h3><div className="grid gap-4 sm:grid-cols-2">{(['firstName','lastName','phone','phone2','email'] as const).map(key=><label key={key} className="block text-sm">{t[key]}{key==='phone2'?'':' *'}<input className="mt-2 w-full rounded-xl border border-ink-24 bg-paper p-3" name={key} required={key!=='phone2'} value={draft[key]} onChange={e=>update(key,e.target.value)} maxLength={key==='email'?150:(key==='phone'||key==='phone2')?24:70} type={key==='email'?'email':(key==='phone'||key==='phone2')?'tel':'text'} autoComplete={{firstName:'given-name',lastName:'family-name',phone:'tel',phone2:'off',email:'email'}[key]}/></label>)}</div>
 <label className="block text-sm">{t.wilaya} *<select name="wilayaId" required value={draft.wilayaId} onChange={e=>update('wilayaId',e.target.value)} className="mt-2 w-full rounded-xl border border-ink-24 bg-paper p-3"><option value="">{t.choose}</option>{deliveryRates.map(rate=><option key={rate.id} value={rate.id} disabled={!rate.available}>{rate.id} — {rate.name[locale]}{!rate.available?` — ${t.unavailable}`:''}</option>)}</select></label>
 <fieldset><legend className="mb-3 text-sm">{t.method} *</legend><div className="grid gap-3 sm:grid-cols-2">{(['home','stopdesk'] as const).map(method=><label key={method} className={`flex items-start gap-3 rounded-xl border p-4 ${draft.deliveryMethod===method?'border-ink':'border-ink-12'}`}><input type="radio" name="deliveryMethod" value={method} checked={draft.deliveryMethod===method} onChange={()=>update('deliveryMethod',method)} className="mt-1"/><span>{t[method]}{draft.wilayaId&&<small className="mt-1 block">{deliveryRates.find(r=>r.id===draft.wilayaId)?.[method]===null?t.unavailable:money(deliveryRates.find(r=>r.id===draft.wilayaId)?.[method]||0,locale)}</small>}</span></label>)}</div></fieldset>
 {draft.deliveryMethod==='home'?<label className="block text-sm">{t.address} *<textarea name="address" required minLength={5} maxLength={300} autoComplete="street-address" value={draft.address} onChange={e=>update('address',e.target.value)} className="mt-2 w-full rounded-xl border border-ink-24 p-3"/></label>:<p className="text-sm text-ink-56">{t.pickup}</p>}
 <label className="block text-sm">{t.note}<textarea name="note" maxLength={1000} value={draft.note} onChange={e=>update('note',e.target.value)} className="mt-2 w-full rounded-xl border border-ink-24 p-3"/></label><input ref={honeypot} name="website" hidden tabIndex={-1} autoComplete="off"/>
 <label className="flex gap-3 text-xs leading-relaxed"><input name="consent" type="checkbox" required checked={draft.consent} onChange={e=>update('consent',e.target.checked)}/>{t.consent}</label>
 <div aria-live="polite">{pricing?<Totals pricing={pricing} locale={locale}/>:<p className="text-sm text-ink-56">{t.selectRate}</p>}</div><button className="w-full rounded-full bg-ink p-4 text-paper">{t.review}</button></form>}{error&&<p role="alert" className="rounded-xl border border-ink-24 p-4 text-sm">{t[error]}</p>}</div>;
}
